-- Create USER Table
DROP TABLE IF EXISTS USER_TABLE;
CREATE TABLE USER_TABLE (
    USER_TABLE_ID TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    NAME TEXT NOT NULL,
    MAIL_ADDRESS TEXT NOT NULL,
    CREATE_TIME TIMESTAMP WITH TIME ZONE,
    UPDATE_TIME TIMESTAMP WITH TIME ZONE
);

-- Create TASK TABLE
DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK (
    TASK_ID UUID NOT NULL,
    TITLE TEXT NOT NULL,
    CREATE_TIME TIMESTAMP WITH TIME ZONE,
    UPDATE_TIME TIMESTAMP WITH TIME ZONE,
    IS_FINISHED BOOLEAN DEFAULT FALSE,
    USER_ID TEXT NOT NULL,
    CATEGORY_ID TEXT
);

-- Create CATEGORY TABLE
DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY (
                      CATEGORY_ID UUID NOT NULL,
                      NAME TEXT NOT NULL,
                      CREATE_TIME TIMESTAMP WITH TIME ZONE,
                      UPDATE_TIME TIMESTAMP WITH TIME ZONE,
                      IS_FINISHED BOOLEAN DEFAULT FALSE,
                      USER_ID TEXT NOT NULL
);