version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: go-todo-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: go-todo-db
    volumes:
      - ./postrges/data/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always